export type DataUtamaProp = {
    id_aju: string;
    nomor_pengajuan: string;
    kegiatan_ke: number;
    kd_pabean_asal: string;
    kd_pabean_pengawas: string | null;
    kd_jenis_ekspor: string | null;
    kd_kategori_ekspor: string | null;
    jenis_ppkek: string;
    jenis_kegiatan: string;
    kd_kegiatan: string;
    kd_transaksi: string;
    kd_cara_bayar: number;
    kd_cara_dagang: string | null;
    tanggal_pengajuan: string;
    nomor_pendaftaran: string | null;
    tanggal_pendaftaran: string | null;
    berat_kotor: string;
    berat_bersih: string;
    kd_skep_fasilitas: string;
    jenis_pib: string;
    kd_jenis_impor: string;
    kd_bc: string | null;
    tgl_bc: string | null;
    nomor_bc: string;
    pos_bc: string;
    sub_pos_bc: string;
    sub_sub_pos_bc: string;
    kode_pembayar: string;
    kd_pengajuan: string | null;
    dok_asal: string | null;
    jenis_transaksi: string | null;
    kategori_transaksi: string | null;
    tujuan_transaksi: string | null;
    asal_barang: string | null;
    kategori_barang: string | null;
    kd_pabean_bongkar: string | null;
    jenis_tpb: string | null;
    kode_kena_pajak: string | null;
    tgl_ttd: string | null;
    ur_pabean_asal: string;
    ur_pabean_pengawas: string;
    ur_jenis_ekspor: string;
    ur_kategori_ekspor: string;
    ur_transaksi: string | null;
    ur_cara_bayar: string;
    ur_cara_dagang: string | null;
    ur_dokumen_penutup: string | null;
    ur_jenis_pib: string;
    ur_jenis_impor: string;
    ur_transaksi_impor: string;
    ur_pabean_bongkar: string;
    ur_jenis_tpb: string | null;
    ur_transaksi_ftz: string | null;
    ur_kena_pajak: string | null;
};
  